services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./server/.env
    environment:
      POSTGRES_DB: reelmark
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres_data:
